version: '3.8'

services:
  markdownview:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: markdownview_app_container
    ports:
      - "5000:5000"
    volumes:
      # Si vous voulez du hot-reloading pendant le développement,
      # vous pouvez monter le répertoire de l'application.
      # Attention: les dépendances système installées via apt dans le Dockerfile
      # ne seront pas affectées par ce montage.
      # Pour la production, il est généralement préférable de ne pas monter le code source
      # et de s'appuyer sur l'image construite.
      # - ./app:/opt/app/app
    restart: unless-stopped
    environment:
      # Vous pouvez ajouter des variables d'environnement ici si nécessaire
      # Par exemple, pour Flask en mode debug (non recommandé en production pure)
      # FLASK_DEBUG: 1
      # Pour Gunicorn:
      # GUNICORN_CMD_ARGS: "--workers=4 --threads=2"
      PYTHONUNBUFFERED: 1 # Déjà dans le Dockerfile, mais peut être redéfini ici