version: '3.8'

services:
  markdownview:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: markdownview_app_container
    ports:
      - "5050:5000" # Port hôte changé à 5050, port conteneur reste 5000
    # volumes: # Commenter la clé elle-même si aucun volume n'est actif
      # - ./app:/opt/app/app # Exemple de volume, correctement formaté en tant qu'élément de liste
    restart: unless-stopped
    environment:
      # Vous pouvez ajouter des variables d'environnement ici si nécessaire
      # Par exemple, pour Flask en mode debug (non recommandé en production pure)
      # FLASK_DEBUG: 1
      # Pour Gunicorn:
      # GUNICORN_CMD_ARGS: "--workers=4 --threads=2"
      PYTHONUNBUFFERED: 1 # Déjà dans le Dockerfile, mais peut être redéfini ici